### PR TITLE
Add Several Commit Messages

### PR DESCRIPTION
**Pull request by amayer5125**
Sort old list. Some messages were not sorted.

### CODE REVIEW

**Comment by amayer5125** [comment]
@ngerakines is there something else I need to do for this to be merged?

**Comment by ngerakines** [comment]
Add yourself to humans.txt!

**Comment by amayer5125** [comment]
Done

**Comment by amayer5125** [comment]
@ngerakines This is good to merge

**Comment by amayer5125** [comment]
@ngerakines I rebased. So this is mergable again.

**Pull request merged**
