### PR TITLE
Adding my boss's funny commit when all test broke

### PR DESCRIPTION
**Pull request by igorsantos07**

### CODE REVIEW

**Comment by hotdang-ca** [comment]
You may also need to re-alphabetize the file per the contribution notes.

**Comment by ngerakines** [comment]
Don't forget to add yourself to humans.txt!

**Comment by igorsantos07** [comment]
Added to `humans.txt` and re-sorted the list. Running sort made a WHOLE BUNCH OF CHANGES. Seems like that rule got forgotten in ages!

**Comment by ngerakines** [comment]
Thanks!

**Pull request merged**
